/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const ShowroomModel = () => {
  const { nodes, materials } = useGLTF("/models/new cloth store.glb");
  return (
    <group scale={10} dispose={null}>
      <group
        position={[4.62, 1.979, 0.041]}
        rotation={[1.61, 0.422, -0.474]}
        scale={0.017}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh014.geometry}
          material={materials.aiStandardSurface3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh014_1.geometry}
          material={materials.light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh014_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh014_3.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh014_4.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh014_5.geometry}
          material={materials["standardSurface4.001"]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002.geometry}
          material={materials["wall_1.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface75.geometry}
        material={materials["wood.001"]}
        position={[1.524, 0.076, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.014}
      />
    </group>
  );
};

export default ShowroomModel;
